### ISSUE TITLE
클러스터별 파이프라인 설계 시각화 및 구현

### ISSUE THREAD

**Issue by SooMiiii** [CheckNanbang/2025-weather-data-contest#17]
내가 생각해본 구조
<img width="1896" alt="Image" src="https://github.com/user-attachments/assets/428d185f-da1c-4794-9e63-9fb5a610d1aa" />

**Comment by SooMiiii** [comment]
# README.md
# 클러스터 기반 머신러닝 파이프라인

클러스터별로 독립적인 머신러닝 모델을 학습하여 예측 성능을 향상시키는 파이프라인입니다.

## 🚀 주요 특징

- **클러스터별 독립 학습**: 사전 정의된 클러스터 매핑에 따라 데이터를 분리하고 각각 독립적으로 모델 학습
- **다양한 모델 지원**: LightGBM, XGBoost 등 주요 머신러닝 모델 지원
- **자동 하이퍼파라미터 튜닝**: Optuna를 활용한 효율적인 하이퍼파라미터 최적화
- **포괄적인 평가**: 다양한 회귀 평가 지표와 시각화 제공
- **유연한 설정 관리**: YAML 기반 설정으로 실험 재현성 보장
- **효율적인 로깅**: 클러스터별 독립적인 로그 관리 및 결과 저장

## 📁 프로젝트 구조

```
├── main.py              # 메인 실행 파일
├── config/
│   └── config.yaml      # 설정 파일
├── src/
│   ├── data/           # 데이터 로딩 및 전처리
│   ├── models/         # 모델 클래스들
│   ├── training/       # 학습 로직
│   ├── evaluation/     # 평가 및 시각화
│   └── utils/          # 유틸리티 함수들
├── scripts/            # 실행 스크립트
├── logs/              # 로그 파일
├── plots/             # 시각화 결과
├── results/           # 실험 결과
├── models/            # 학습된 모델
└── submissions/       # 제출 파일
```

## 🛠️ 설치 및 설정

1. **의존성 설치**
```bash
pip install -r requirements.txt
```

2. **설정 파일 생성**
```bash
python scripts/create_config.py --output config/config.yaml
```

3. **데이터 준비**
```
data/
├── train_heat.csv
├── test_heat.csv
└── sample_submission.csv
```

## 🎯 사용법

### 기본 실행
```bash
# 모든 클러스터 학습
python main.py

# 특정 클러스터만 학습
python main.py --clusters 0 1

# 설정 파일 지정
python main.py --config custom_config.yaml
```

### 스크립트를 통한 실행
```bash
# 실험 실행
python scripts/run_experiment.py --clusters 0 1 2

# 설정 확인 (dry-run)
python scripts/run_experiment.py --dry-run

# 상세 로그와 함께 실행
python scripts/run_experiment.py --verbose
```

## ⚙️ 설정 파일 구조

```yaml
experiment:
  name: "heat_demand_prediction"
  version: "v1.0"
  description: "클러스터별 열 수요 예측"

data:
  dataset_name: "heat"
  target_column: "heat_demand"
  data_path: "data"

cluster:
  mapping:
    0: ['E', 'K', 'R', 'S']
    1: ['F', 'I', 'J', 'L', 'M', 'N', 'O', 'P', 'Q']
    2: ['A', 'B', 'C', 'D', 'G', 'H']

training:
  models: ["LGBM", "XGB"]
  tune_hyperparams: true
  n_trials: 20
```

## 📊 결과 분석

실험 완료 후 다음과 같은 결과물이 생성됩니다:

- **로그 파일**: `logs/experiment_MMDD_HHMMSS.log`
- **성능 메트릭**: `results/{experiment_id}/cluster_metrics.json`
- **시각화**: `plots/{experiment_id}/cluster_{id}/`
- **제출 파일**: `submissions/{experiment_id}_submission.csv`
- **종합 리포트**: `results/{experiment_id}/experiment_report.md`

## 🔧 확장 가능성

### 새로운 모델 추가
1. `src/models/`에 새 모델 클래스 생성
2. `BaseModel`을 상속받아 구현
3. `ModelFactory`에 모델 등록

### 전처리 로직 수정
`src/data/preprocessor.py`의 각 메서드를 수정하여 도메인별 전처리 적용

### 평가 지표 추가
`src/evaluation/evaluator.py`에서 새로운 평가 지표 및 시각화 추가

## 🐛 문제 해결

### 일반적인 문제들

1. **메모리 부족**
   - 배치 크기 조정 또는 데이터 샘플링

2. **수렴 문제**
   - 학습률 조정 또는 early stopping 파라미터 수정

3. **로그 파일 권한 오류**
   - 로그 디렉토리 권한 확인

## 📈 성능 최적화 팁

1. **클러스터별 특성 고려**: 각 클러스터의 데이터 특성에 맞는 전처리 적용
2. **하이퍼파라미터 튜닝**: 충분한 trial 수로 최적 파라미터 탐색
3. **앙상블 활용**: 여러 모델의 예측 결과를 조합하여 성능 향상
4. **특성 엔지니어링**: 도메인 지식을 활용한 파생 변수 생성
